### ISSUE TITLE
ES6 in webpack.prod.config

### ISSUE THREAD

**Issue by d0ruk** [DominicTobias/universal-react#1]
Hello,

I solved it with a babel-register.js at root and modifying changing the "npm run build" script's config to "babel-register.js"

``` javascript
require('babel/register');
module.exports = require('./webpack.production.config.js');
```

``` javascript
"build": "NODE_ENV=production webpack --config ./babel-register.js --progress --profile --colors"
```

**Comment by dominictobias** [comment]
HI @Norm- I was just thinking about this - it will work with Node v4 but not older versions before the io.js merge. It's actually pretty unnecessary to have the "Clean" plugin as a class so I think I might just write it as an ES5 plugin. Thanks for the heads up. My advice is to upgrade your version of node though :)

**Comment by dominictobias** [comment]
Actually I think that soon nobody will be using pre Node v4 for much longer (latest is 4.2.1), I recommend you update too. So leaving this as a class as it's cleaner. Thanks for the input.
