### ISSUE TITLE
Error: Cannot find module './routes'

### ISSUE THREAD

**Issue by pfulop** [DominicTobias/universal-react#10]
After install and start, there is error of missing module.

`Error: Cannot find module './routes'
`

To fix this, you need to correct typo on line 6 in app/Router.js './routes.js' => './Routes.js' .

**Comment by dominictobias** [comment]
Thanks @pfulop I'll change it, out of curiosity what node version are you using? (it was working for me case-insensitively so just wondering)

**Comment by dominictobias** [comment]
Pushed to master, will go in the next release too.

**Comment by pfulop** [comment]
@DominicTobias Hi, I have been using v5.7.0
