### ISSUE TITLE
Update history version

### ISSUE THREAD

**Issue by sallad-tlm** [DominicTobias/universal-react#11]
history version 2.0.0 gives this error 
npm ERR! peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

history version to 2.0.1 works just file.

**Comment by dominictobias** [comment]
Thanks @sallad-tlm, I've updated the dependency
