### ISSUE TITLE
app/index.js: Unexpected token (2:7)

### ISSUE THREAD

**Issue by AmenRa** [DominicTobias/universal-react#14]
Hello, when i run "npm start" i got an error: 

```
SyntaxError: /Volumes/Mac Data/Users/Elias/noteshare/app/index.js: Unexpected token (2:7)
  1 | import 'isomorphic-fetch';
> 2 | export serverMiddleware from './Router';
    |        ^
```

Here my log: 
[npm-debug copy.txt](https://github.com/DominicTobias/universal-react/files/234963/npm-debug.copy.txt)

Any ideas?

**Comment by dominictobias** [comment]
Hi, what version of node are you using?

**Comment by AmenRa** [comment]
I found the problem, i don't know why the .babelrc file haven't been downloaded along with the other files...

**Comment by dominictobias** [comment]
Ah cool, interesting (and strange)!

**Comment by AmenRa** [comment]
I got the same problem with another react boilerplate today, i don't know if it's an unzip error on mac or what...
