### ISSUE TITLE
Hot reload not working (windows 8.1)

### ISSUE THREAD

**Issue by awhitehouse104** [DominicTobias/universal-react#21]
Can't speak for everyone, but I had to modify a couple of things to get hot reload to work on windows.

First, remove localhost binding in server.js ([reference](https://github.com/gaearon/react-transform-boilerplate/pull/111)).

``` javascript
server.listen(port, (err) => {
    if (err) {
        console.error(err);
    }
    console.info('==> 🌎 Listening on port %s. Open up http://localhost:%s/ in your browser.', port, port);
});
```

Also, add base public path in webpack.config ([reference](https://github.com/webpack/webpack/issues/497#issuecomment-56948560)).

``` javascript
output: {
    path: path.join(__dirname, 'dist'),
    filename: 'app.js',
    publicPath: '/'
},
```

**Comment by dominictobias** [comment]
Excellent thanks, it was never working well for me good catches, note that it still won't work with react pure functional components but that's a limitation of the hot reloader (looking forward to the [new one](https://github.com/gaearon/react-hot-loader#a-big-update-is-coming)). I'll verify this later and update.

**Comment by awhitehouse104** [comment]
Yes I considered playing with the new one but this fix was simple enough for now :)
