### ISSUE TITLE
What about styles?

### ISSUE THREAD

**Issue by SudoPlz** [DominicTobias/universal-react#26]
How does this boilerplate handle styles in the server and the client? 
I see no css, scss, less etc.

**Comment by dominictobias** [comment]
There was once a sass solution but there are too many to decide for you - have you ever used styles with webpack? My approach would be as normal - add `css-loader`, `style-loader` and e.g. postcss-loader and import css into component files. In the production build use webpack's `extract-text-webpack-plugin` to extract all styles to the dist folder, and in Root.js if it's a production env then load it in. Any questions let me know - but check those packages on github and they should give you an idea.
