### ISSUE TITLE
Had to downgrade to React-Router v3.0.5

### ISSUE THREAD

**Issue by jturbo26** [DominicTobias/universal-react#32]
I was getting an error "_reactRouter.match is not a function" when attempting to install and start the server. In order to get around this error I had to downgrade React-Router from v4.1.2 to v3.0.5. There were several breaking changes introduced from v3 to v4 and this repo only worked on v3.

**Comment by dominictobias** [comment]
Thanks this was a mistake when upgrading some deps, will downgrade it
