### ISSUE TITLE
Unable to hot reload React Components

### ISSUE THREAD

**Issue by josephktcheung** [DominicTobias/universal-react#9]
Thanks for creating this starter kit!

I could not hot-reload React component, which I think is because of the [changes here](https://github.com/DominicTobias/universal-react/commit/41abfb2183464f08a94c15b6f447bf8e82a5fe96#diff-11e9f7f953edc64ba14b0cc350ae7b9dL28)

Can I know why it is removed? Thanks.

**Comment by dominictobias** [comment]
Oops thanks for pointing this out @josephktcheung ! Fixed (not npm published yet as there's another improvement coming to do with handling failed app api requests which happen during the server render)

**Comment by josephktcheung** [comment]
Welcome! Looking forward to next update!

**Comment by dominictobias** [comment]
Thanks, np, also I added hot reloading for reducers today (I realised that doesn't automatically happen). You can add it to your project like this: https://github.com/DominicTobias/universal-react/blob/master/app/configureStore.js
